version: "3" # Verze Docker Compose
services:
    frontend:
        build: # Kde se má Docker compose hledat složky Dockerfile
            context: ./frontend
        ports: # Definice portu pro frontend
            - "8000:3000"
        volumes: # Synchronizace mezi souborovými systémem
            - ./frontend:/app
        depends_on: # Definuje závislost na backendu, pokud již neběží tak ho zapne
            - backend

    backend:
        build:
            context: ./backend
        ports:
            - "8001:8001"
        volumes:
            - ./backend:/app
