services:
    - name: frontend
      env: production
      buildCommand: docker build -t render-frontend ./frontend
      startCommand: docker run -p 8000:8000 render-frontend
      ports:
          - 8000

    - name: backend
      env: production
      buildCommand: docker build -t render-backend ./backend
      startCommand: docker run -p 8001:8001 render-backend
      ports:
          - 8001
