version: "3"
services:
    frontend:
        build:
            context: ./frontend
        ports:
            - "8000:3000"
        volumes:
            - ./frontend:/app
        depends_on:
            - backend

    backend:
        build:
            context: ./backend
        ports:
            - "8001:8001"
        volumes:
            - ./backend:/app
