services:
  - name: backend
    buildCommand: |
      pip install -r backend/requirements.txt
      cd backend
      python manage.py collectstatic --noinput
    startCommand: gunicorn taxes.wsgi:application --workers 4 --bind 0.0.0.0:8001
