services:
  - name: backend
    buildCommand: |
      cd backend  # Change to the backend directory
      pip install -r requirements.txt  # Install dependencies
      python manage.py collectstatic --noinput  # Collect static files
    startCommand: gunicorn taxes.wsgi:application --workers 4 --bind 0.0.0.0:8001
