# Generated by Django 4.2.3 on 2023-07-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_email_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='suggestion',
        ),
    ]
