# Generated by Django 4.2.3 on 2023-07-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0004_email_last_updated_email_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='email',
            name='message',
        ),
        migrations.RemoveField(
            model_name='email',
            name='sent_at',
        ),
    ]
