# Generated by Django 4.2.3 on 2023-07-14 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0005_remove_email_last_updated_remove_email_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='email',
            name='message',
            field=models.TextField(default='Message empty'),
        ),
        migrations.AddField(
            model_name='email',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
