# Generated by Django 4.2.3 on 2023-07-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0008_alter_email_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='last_updated',
        ),
    ]
